import express from 'express';
import rateLimit from 'express-rate-limit';
import auth from '../middleware/auth.js';
import { calculateCarbonScore } from '../services/carbonScore.js';
import { profilesRepo, activitiesRepo, recommendationSetsRepo } from '../db/repos.js';
import { buildFallbackRecommendations, recommendationInputFingerprint } from '../services/recommendations.js';
import { GEMINI_NOT_CONFIGURED_NOTICE, describeGeminiFailure, isGeminiConfigured } from '../services/geminiClient.js';
import { generateAndSaveRecommendations } from '../services/recommendationRunner.js';
import { recommendationRefresh } from '../services/recommendationRefresh.js';
import { CATEGORY_LABELS, EMISSION_FACTORS, factorFor } from '../config/emissionFactors.js';

const router = express.Router();

// Each generation is a paid Gemini call; this only stops runaway loops or abuse
const generationLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 30,
  standardHeaders: true,
  legacyHeaders: false,
  skip: () => process.env.NODE_ENV === 'test',
  message: { error: 'Too many recommendation requests. Please wait a few minutes and try again.' }
});

const isNonNegativeNumber = (value) => typeof value === 'number' && Number.isFinite(value) && value >= 0;

/** Validate the client-computed emissions payload; null when malformed. */
function parseEmissionsData(data) {
  if (!data || !isNonNegativeNumber(data.total_emissions_tons_co2e)) return null;
  const breakdown = data.breakdown;
  if (!breakdown || typeof breakdown !== 'object' || Array.isArray(breakdown)) return null;
  if (!Object.values(breakdown).every(isNonNegativeNumber)) return null;
  return {
    total: data.total_emissions_tons_co2e,
    rating: typeof data.carbon_rating === 'string' ? data.carbon_rating : null,
    breakdown
  };
}

// Activity types and their factors, using the company's state grid rate so
// the factor shown when adding an activity matches the one the score uses
router.get('/emission-factors', auth, async (req, res) => {
  try {
    const state = profilesRepo.findByUserId(req.userId)?.state;
    const emissionFactors = Object.fromEntries(
      Object.entries(EMISSION_FACTORS).map(([sector, items]) => [
        sector,
        Object.fromEntries(
          Object.entries(items).map(([subsector, item]) => [subsector, { ...item, factor: factorFor(sector, subsector, { state }) }])
        ),
      ])
    );

    res.json({
      sectors: Object.keys(EMISSION_FACTORS),
      categories: CATEGORY_LABELS,
      emission_factors: emissionFactors
    });
  } catch (error) {
    console.error('Error fetching emission factors:', error);
    res.status(500).json({ error: 'Error fetching emission factors' });
  }
});

// Carbon calculator
router.post('/carbon-calculator', auth, async (req, res) => {
  try {
    const { company_name, activities } = req.body;

    if (!activities || !Array.isArray(activities)) {
      return res.status(400).json({ error: 'Activities array is required' });
    }

    const score = calculateCarbonScore(
      activities.map((activity) => ({
        sector: activity.sector,
        subsector: activity.subsector,
        amount: activity.activity_amount,
        date: activity.activity_date ?? null
      })),
      profilesRepo.findByUserId(req.userId)
    );

    res.json({ company_name, ...score });
  } catch (error) {
    console.error('Carbon calculator error:', error);
    res.status(500).json({ error: 'Error calculating carbon score' });
  }
});

// Carbon reduction recommendations generated by Gemini
router.post('/carbon-recommendations', generationLimiter, auth, async (req, res) => {
  const { industry: requestedIndustry, emissions_data: emissionsData, selected_sectors: selectedSectors } = req.body;

  const emissions = parseEmissionsData(emissionsData);
  if (!emissions) {
    return res.status(400).json({
      error: 'emissions_data must include a non-negative total_emissions_tons_co2e and a breakdown of non-negative sector totals'
    });
  }

  try {
    const companyProfile = profilesRepo.findByUserId(req.userId);
    // The saved profile is the source of truth; the request value only covers
    // users who haven't created a profile yet.
    const industry = companyProfile?.industry || requestedIndustry;
    if (!industry) {
      return res.status(400).json({ error: 'Industry is required. Complete your company profile first.' });
    }

    const fallback = (notice) => ({
      ...buildFallbackRecommendations({ industry, totalEmissions: emissions.total }),
      ...(notice ? { notice } : {})
    });

    if (!isGeminiConfigured()) {
      console.warn('GEMINI_API_KEY is not set; using fallback recommendations');
      return res.json(fallback(GEMINI_NOT_CONFIGURED_NOTICE));
    }

    const focusSectors = Array.isArray(selectedSectors)
      ? selectedSectors.filter((sector) => Object.hasOwn(emissions.breakdown, sector))
      : [];

    // Only real Gemini results are saved; a fallback set is shown but not
    // kept, so a temporary outage never replaces good saved recommendations.
    try {
      const activities = activitiesRepo.findByUserId(req.userId);
      const result = await generateAndSaveRecommendations({
        userId: req.userId,
        profile: companyProfile,
        industry,
        emissions,
        activities,
        focusSectors
      });
      // A queued background refresh is now redundant, unless the data changed
      // while Gemini was working
      const generatedFrom = recommendationInputFingerprint({ profile: companyProfile, activities });
      const current = recommendationInputFingerprint({
        profile: profilesRepo.findByUserId(req.userId),
        activities: activitiesRepo.findByUserId(req.userId)
      });
      if (generatedFrom === current) recommendationRefresh.cancel(req.userId);
      return res.json(result);
    } catch (geminiError) {
      console.error('Gemini recommendations failed; using fallback:', geminiError.message);
      return res.json(fallback(describeGeminiFailure(geminiError)));
    }
  } catch (error) {
    console.error('Carbon recommendations error:', error);
    res.status(500).json({ error: 'Error generating recommendations' });
  }
});

// Most recently saved recommendations, flagged if the company's data changed since
router.get('/carbon-recommendations/latest', auth, async (req, res) => {
  try {
    const saved = recommendationSetsRepo.findByUserId(req.userId);
    if (!saved) {
      return res.json({ saved: null });
    }

    const currentFingerprint = recommendationInputFingerprint({
      profile: profilesRepo.findByUserId(req.userId),
      activities: activitiesRepo.findByUserId(req.userId)
    });

    res.json({
      saved: {
        ...saved.payload,
        generated_at: saved.updatedAt,
        is_outdated: saved.inputFingerprint !== currentFingerprint,
        // A background refresh is queued or running after a recent data change
        refreshing: recommendationRefresh.isPending(req.userId)
      }
    });
  } catch (error) {
    console.error('Get saved recommendations error:', error);
    res.status(500).json({ error: 'Error fetching saved recommendations' });
  }
});

export default router; 